# Installation of numpy

In [56]:
pip install numpy

# Importing Numpy

In [57]:
import numpy as np

# Creating Numpy Arrays

In [58]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [59]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [60]:
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [61]:
ones = np.ones((2,2))
print(ones)

[[1. 1.]
 [1. 1.]]


# Array Attributes

In [62]:
np.shape(arr)

(5,)

In [63]:
np.ndim(ones)

2

In [64]:
np.size(zeros)

9

# Indexing and Slicing Arrays

In [65]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[-1])
print(arr[2:4])

1
5
[3 4]


# Array Operations

In [66]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[1 4 9]


# Broadcasting


In [67]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2
print(arr1 * scalar)

[[ 2  4  6]
 [ 8 10 12]]


# Reshaping Arrays

In [68]:
arr = np.arange(1, 10)
reshaped = arr.reshape(3, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
arr = np.arange(1, 10)
flattened = arr.flatten()
print(flattened)

[1 2 3 4 5 6 7 8 9]


In [70]:
arr = np.arange(1, 10)
raveled = arr.ravel()
print(raveled)

[1 2 3 4 5 6 7 8 9]


# Joining  Arrays

In [71]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated = np.concatenate((arr1, arr2))
stacked = np.stack((arr1, arr2))
vstacked = np.vstack((arr1, arr2))
hstacked = np.hstack((arr1, arr2))
print(concatenated)
print(stacked)
print(vstacked)
print(hstacked)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# Changing Array Data Types

In [72]:
arr = np.array([1, 2, 3], dtype=np.float64)
new_arr = arr.astype(np.int32)
print(new_arr)

[1 2 3]


# Sorting and Searching Arrays

In [73]:
arr = np.array([1, 7, 9, 4, 2 ])
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 4 7 9]


In [74]:
arr = np.array([1, 2, 3])
print(np.square(arr))
print(np.sqrt(arr))
print(np.exp(arr))

[1 4 9]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]


# trigonometric Functions

In [75]:
arr = np.array([0, np.pi / 2, np.pi])
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


# Exponential and Logarithmic Functions

In [76]:
arr = np.array([1, 10, 100])
print(np.exp(arr))
print(np.log(arr))
print(np.log10(arr))

[2.71828183e+00 2.20264658e+04 2.68811714e+43]
[0.         2.30258509 4.60517019]
[0. 1. 2.]


# Statistical Functions

In [77]:
arr = np.array([1, 7, 9, 4, 2 ])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

4.6
4.0
3.0066592756745814


# LinearAlgebra Operations

In [78]:
matrix = np.array([[1, 2], [3, 4]])
print(np.dot(matrix, matrix))
print(np.transpose(matrix))

[[ 7 10]
 [15 22]]
[[1 3]
 [2 4]]


# Saving and Loading Arrays

In [79]:
arr = np.array([1, 7, 9, 4, 2 ])
np.save('array.npy', arr)
loaded_arr = np.load('array.npy')
print(loaded_arr)

[1 7 9 4 2]


In [80]:
arr = np.array([1, 7, 9, 4, 2 ])
np.savetxt('array.txt', arr)
loaded_arr = np.loadtxt('array.txt')
print(loaded_arr)

[1. 7. 9. 4. 2.]


# Binary File Input and Output

In [81]:
arr = np.array([1, 7, 9, 4, 2 ])
np.save('array.npy', arr)
loaded_arr = np.load('array.npy')
print(loaded_arr)

[1 7 9 4 2]


# Compressed File Input and Output

In [82]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

np.savez('arrays.npz', arr1 = arr1, arr2 = arr2)
loaded_data = np.load('arrays.npz')
print(loaded_data['arr1'])
print(loaded_data['arr2'])

[1 2 3]
[4 5 6]


# Broadcasting in Depth

In [83]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2
print(result)

[[11 22 33]
 [14 25 36]]


# Array Manipulation Tricks

In [84]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed = arr.T
repeated = np.repeat(arr, 2, axis=0)
stacked = np.stack((arr, arr), axis=0)
print(transposed)
print(repeated)
print(stacked)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Fancy Indexing and Boolean Masking


In [85]:
arr = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 4])
print(arr[indices])
mask = arr > 2
print(arr[mask])

[1 3 5]
[3 4 5]


# Structured Arrays

In [88]:
dt = np.dtype([('name', np.str_, 16), ('age', np.int32), ('salary', np.float64)])
arr = np.array([('jhon', 25, 5000.0), ('alice', 30, 6000.0)], dtype = dt)
print(arr['name'])
print(arr['age'])
print(arr['salary'])

['jhon' 'alice']
[25 30]
[5000. 6000.]


# Universal Functions

In [89]:
arr = np.array([1, 2, 3])
print(np.add(arr, 2))

print(np.multiply(arr, 2))

print(np.sqrt(arr))

[3 4 5]
[2 4 6]
[1.         1.41421356 1.73205081]


# Vectorization

In [90]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


# Memory Efficiency

In [94]:
arr1 = np.array([1, 2, 3])
arr2  = arr1
view  = arr1.view()#creating view (no additional memory)..it changes if we upadate an value
copy  = arr1.copy()#createing copy (additional memory)..it does not changes if we upadate an value
print(view)
print(copy)

[1 2 3]
[1 2 3]


# Use Numpy Instead Of Loops

In [95]:
arr = np.array([1, 2, 3, 4, 5])
total = np.sum(arr)
print(total)

15


# Additional operations

In [96]:
arr = np.linspace(1,10,20)
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [97]:
arr=np.random.rand(5,5)
arr

array([[0.76820719, 0.77730332, 0.45521084, 0.33069208, 0.84175361],
       [0.11996914, 0.97539675, 0.71240927, 0.10897594, 0.65786625],
       [0.88714715, 0.03867037, 0.92732226, 0.83224537, 0.62914601],
       [0.46890718, 0.3899407 , 0.5218009 , 0.77220544, 0.57422274],
       [0.05388274, 0.68440513, 0.26445021, 0.88381461, 0.81690843]])

In [98]:
mat1=np.array([[1,2],[3,4]])
print(mat1)

[[1 2]
 [3 4]]


In [99]:
mat1[0][0]=5
print(mat1)

[[5 2]
 [3 4]]


In [101]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
np.min(a,axis=1)#col wise 

array([1, 4])

In [103]:
np.min(a,axis=0)#row wise

array([1, 2, 3])

In [105]:
d=np.array([10,20,50,30,60])
d

array([10, 20, 50, 30, 60])

In [106]:
np.searchsorted(d,[10,60])#sort the elements and search for the values

array([0, 4], dtype=int64)

In [107]:
a=np.arange(10,130,10).reshape(4,3)
a

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [108]:
np.where(a==80)#returns the location of the value

(array([2], dtype=int64), array([1], dtype=int64))

In [110]:
c=np.arange(10,110,10)
c

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [111]:
np.split(c,2)#split into 2 parts

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]